title:       "MFH"
name:        "Muhammad Fuad Hasan's Archive"
email:       "m@fuadhasan.org"
description: ""

baseurl:     ""
url:         "http://fuadhasan.org"

permalink:   /:title
exclude:     [Rakefile, README.md, create_index.sh]
