title:       "MFH"
name:        "Welcome to my humble electronic abode!"
author:      "Muhammad Fuad Hasan"
email:       "hasan@mfhasan.net"
description: ""

baseurl:     ""
url:         "http://fuadhasan.org"

permalink:   /:title
exclude:     [Rakefile, README.md, create_index.sh]
