title:       "Hasan's Text Archives"
name:        "Welcome to my humble electronic abode!"
author:      "Muhammad Fuad Hasan"
email:       "mfh@narestu.my.id"
description: ""

baseurl:     ""
url:         "http://fuadhasan.org"

permalink:   /:title
exclude:     [Rakefile, README.md, create_index.sh]
